---
#Common project parameters
az_project_name: "hsl-jore4"
az_project_subdomain: "jore.hsl.fi"
az_region_name: "westeurope"
az_resource_group_name: "{{ az_project_name }}-{{ az_environment }}"

#Common packages
default_packages:
  - anacron
