---
#Common project parameters
az_project_name: "hsl-jore4"
az_project_domain: "jore.hsl.fi"
az_region_name: "westeurope"
az_resource_group_name: "{{ az_project_name }}-{{ az_environment }}"
az_common_resource_group_name: "{{ az_project_name }}-common"

#Common packages
default_packages:
  - anacron

# Networking
az_route_table_name: "jore4-route"
az_vnet_addr_prefix: "{{ cidr_prefix }}.0/24"
az_private_subnet_addr_prefix: "{{ cidr_prefix }}.0/25"
az_private_subnet_router_ip: "{{ cidr_prefix }}.1"  # In Azure always ".1", see https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#are-there-any-restrictions-on-using-ip-addresses-within-these-subnets
az_private_aci_subnet_addr_prefix: "{{ cidr_prefix }}.128/26"
az_public_subnet_addr_prefix: "{{ cidr_prefix }}.232/29"
az_gateway_subnet_addr_prefix: "{{ cidr_prefix }}.240/28"
az_jore3_db_net: "10.218.6.0/27"

# Bastion host
az_initial_ssh_public_key: "{{ lookup('file', '~/.ssh/ansible_initial_key_rsa.pub') }}"
az_hardened_vm_image: # Note that this image has tight iptables firewall rules which are ok for a bastion, but will need to be customized for you service if used on other hosts
  publisher: "center-for-internet-security-inc"
  offer: "cis-ubuntu-linux-1804-l1"
  sku: "cis-ubuntu1804-l1"
  version: "latest"
az_hardened_vm_plan:
  name: "cis-ubuntu1804-l1"
  product: "cis-ubuntu-linux-1804-l1"
  publisher: "center-for-internet-security-inc"
az_initial_username: "hsladmin"
