apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jore4-ingress
  namespace: hsl-jore4
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: jore4-backend
              servicePort: 80
