---
- block:
    - name: "Retrieve the jore4-platform-developers AD group id"
      shell: "az ad group show --group jore4-platform-developers --output tsv --query objectId"
      delegate_to: localhost
      become: false
      run_once: true
      register: ad_group_id

    - name: Create Azure Deployment for the AKS cluster
      azure_rm_deployment:
        resource_group: "{{ az_resource_group_name }}"
        location: "{{ az_region_name }}"
        name: "azure_aks"
        parameters:
          project:
            value: "{{ az_project_name }}"
          environment:
            value: "{{ az_environment }}"
          trustedAdminAddresses:
            value: "{{ az_bastion_host_trusted_ips }}"
          initialNodeCount:
            value: "{{ az_aks_initial_node_count }}"
          aadAdminGroupId:
            value: "{{ ad_group_id.stdout }}"
        tags:
          ansible: workaround
        template: "{{ lookup('file', 'templates/aks.arm.json') }}"
      register: aks_output
    - name: Show deployment outputs
      debug:
        var: aks_output.deployment.outputs
      run_once: true
  tags:
    - deploy-cluster

# Add missing role assignments for Application Gateway Ingress Controller managed identity
- name: Make AGIC contributor of target Application Gateway
  command: "az role assignment create --role Contributor --assignee-object-id {{ aks_output.deployment.outputs.agicPrincipalId.value }} --scope {{ aks_output.deployment.outputs.appgwRef.value }}"
  delegate_to: localhost
  become: false
  run_once: true
  tags:
    - agic-preview-fixes
- name: Make AGIC reader of target resource group
  command: "az role assignment create --role Reader --assignee-object-id {{ aks_output.deployment.outputs.agicPrincipalId.value }} --resource-group {{ az_resource_group_name }}"
  delegate_to: localhost
  become: false
  run_once: true
  tags:
    - agic-preview-fixes
- name: Make AGIC managed identity operator of target Application Gateway's linked scope
  command: "az role assignment create --role 'Managed Identity Operator' --assignee-object-id {{ aks_output.deployment.outputs.agicPrincipalId.value }} --scope {{ aks_output.deployment.outputs.appgwLinkedScopeRef.value }}"
  delegate_to: localhost
  become: false
  run_once: true
  tags:
    - agic-preview-fixes

# Add missing role assignments for ACI Connector managed identity (possibly bug with non-portal deployment, see https://github.com/Azure/AKS/issues/1894 for clues)
- name: Make ACI Connector network contributor of target subnet
  command: "az role assignment create --role 'Network Contributor' --assignee-object-id {{ aks_output.deployment.outputs.aciconnectorPrincipalId.value }} --scope {{ aks_output.deployment.outputs.aciSubnetRef.value }}"
  delegate_to: localhost
  become: false
  run_once: true
  tags:
    - aci-fixes

# Set up VMSS identity to access key-vault
# https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/system-assigned-msi-mode/
- block:
    - name: "Get the name of the Virtual Machine Scale-Set for the cluster"
      shell: "az vmss list --resource-group {{ az_resource_group_name }}-cluster-nodes --query '[].name' --output tsv"
      register: vmss_name

    - debug:
        msg: "{{vmss_name.stdout}}"

    - name: "Enable system-assigned identity for VMSS"
      shell: "az vmss identity assign --resource-group {{ az_resource_group_name }}-cluster-nodes --name {{vmss_name.stdout}} --query 'systemAssignedIdentity' --output tsv"
      register: vmss_identity_id

    - debug:
        msg: "{{vmss_identity_id.stdout}}"

    - name: "Allow VMSS identity to get secrets from key-vault"
      shell: "az keyvault set-policy --secret-permissions get --name {{ az_resource_group_name }}-vault --object-id {{vmss_identity_id.stdout}}"
      register: vmss_identity

  tags:
    - keyvault-identity-binding
