# Workflow file for auto-assign reviewers github action
# See: https://github.com/marketplace/actions/auto-assign-review-teams

name: "Auto-Assign Reviewers"
on:
  pull_request:

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@v1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: "HSLdevcom/jore4"       # only works for GitHub Organisation/Teams
        include-draft: false            # Draft PRs will be skipped (default: false)
        skip-with-manual-reviewers: 1   # Skip this action, if the number of reviwers was already assigned
