# general linter for many languages and tools
# https://github.com/github/super-linter
name: Flux test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test-kustomizations:
    name: Test whether all kustomizations build fine
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs kustomization builds for all cluster environments
      - name: Run Kustomization build for dev flux-system
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "4.0.4"
          kustomize_build_dir: "./clusters/dev/flux-system"

      - name: Run Kustomization build for dev hsl-jore4
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "4.0.4"
          kustomize_build_dir: "./clusters/dev/hsl-jore4"

      - name: Run Kustomization build for test flux-system
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "4.0.4"
          kustomize_build_dir: "./clusters/test/flux-system"

      - name: Run Kustomization build for test hsl-jore4
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "4.0.4"
          kustomize_build_dir: "./clusters/test/hsl-jore4"

      - name: Run Kustomization build for prod flux-system
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "4.0.4"
          kustomize_build_dir: "./clusters/test/flux-system"

      - name: Run Kustomization build for prod hsl-jore4
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "4.0.4"
          kustomize_build_dir: "./clusters/test/hsl-jore4"
